version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notas_db
    restart: always
    environment:
      POSTGRES_DB: notas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaaa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: notas_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: aaaa
    stdin_open: true
    tty: true

volumes:
  postgres_data: